language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - $HOME/.npm
  - $HOME/.cache
before_install:
- npm config set spin false
- npm install -g bower
- bower --version
- npm install phantomjs-prebuilt
- node_modules/phantomjs-prebuilt/bin/phantomjs --version
install:
- npm install
- bower install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: XA55mMUcLw+yJ3cSIcV9wde/yMPIIYwPaCWqUohofeUavbMYkhYJ4okJOjbYDnJZ8njvBM8CoPMtIDt3CZng2KcmCXJ6vu9DxejaW8qvA/hqm0JDhI3FD6i78QcG4vW5NOyUXajd44U4+xnU2ANcEyS5w8heV/F+uPdmbtOivqGmgC4ryX5bYCfL7jrFYUkOy8uW5sP96u4Jon9LYxSh0kzd7sQ6K/gQngngrMjfQpufFpjmTzoOxXuSmRb/IRLLMYOs6prRblnHwk7N9nA+JRxWdtUGTMXrQydxL7bCGe5VFZKCd0HPByNTWBsYhMoGlTGLddP6Jttq/s2axDShXpqPiuivsPONRar3ZfX7uazkKIrEj85OOQxB3PauoDQb3N5FHYHN0nS5cY5gEacObdLr+l2CNdDzeK+kWMDDB2RMAolkCInEg2/avQZm8E8yGzDjm/+gYMqypajZr+KBxCfKf0mLiE76o7yt8EX1ZE16N0G0exOgZEexn1Or877PGbNxgPV9lncg1r84fLCqw1x0DSYhKpSOlgjCrksVeemWV2UqTUo0uhFITCXlC+KGCbqAq8V5nw1ROjZOQDJXcmLV6anYALAc7YjoyoebROugm+0BSo9g15PWqRBR/bqM1ixkkt6F5PHVlI6SA9MGlTf8czeTB60FpYbbZsARmLY=
  app: fem-ember-commently
  on:
    repo: thnima/fem-ember-commently
